### ISSUE TITLE
Add linting

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/GQL#10]
Would be good to get the same linting in place here as we have in [Ghost](https://github.com/TryGhost/Ghost).

**Comment by acburdine** [comment]
I can take care of this if wanted

**Comment by ErisDS** [comment]
:+1: help is always wanted.

From @cwonrails

> For the GQL linting are you looking for the dotfiles + appropriate Grunt tasks from Ghost master?

It should either be exactly the same setup as Ghost, or if someone has an idea for a new tool or setup that might supersede the awkward jshint+jscs combo, but have roughly the same results, I'm fine with this being used as a testbed :)

**Comment by hoxoa** [comment]
What do you think of `ESLint`?
* http://www.sitepoint.com/comparison-javascript-linting-tools/
* https://www.exratione.com/2015/07/eslint-as-a-replacement-for-jshint-and-jscs/

**Comment by cwonrails** [comment]
Love it.

**Comment by ErisDS** [comment]
> Love it.

These sorts of comments are really not constructive. Please qualify your opinions with something that adds value to the conversation.
