### ISSUE TITLE
JSON API

### ISSUE THREAD

**Issue by laran** [TryGhost/GQL#18]
To flesh out changes from #17.

I'm going to think of this as more of a conversation than a full spec in one shot.

I've written up docs over in [the wiki](https://github.com/laran/GQL/wiki) where I did this work. In the wiki I gave examples to show what the GQL string syntax for a part of a query looks like along with the equivalent JSON and SQL. If you read the wiki with those goggles on while thinking about the JSON API it may seem more relevant. I'll summarize some here though.

I'll use the term `filter` because I think we have some context around that term. And when I refer to a filter I'll be speaking about a JSON object (which could have been created by calling `gql.parse()` on a string).

A filter is an array of JSON objects, each of which represents a [condition](https://github.com/laran/GQL/wiki/Conditions). In the special case that a filter contains only a single condition it will be a single JSON object and not an array of objects.
### Conditions

The conditions in a filter are related by boolean logic, either AND or OR. AND conditions look like `{title: 'Hello World!'}` while OR conditions looks like `{$or: {title:`Hello World!'}}. When the filter is an array of objects it's expected that the first element in the array is NOT an `$or` condition.

Each condition is made up of a [property](https://github.com/laran/GQL/wiki/Properties), a [comparison operator](https://github.com/laran/GQL/wiki/Comparison-Operators) and a [value](https://github.com/laran/GQL/wiki/GQL-Syntax#value).

The simplest condition is an equals condition which is simply `{title: Home}`.

Other types of conditions are all written in a similar way. For example: less than is written like this `{amount: {$lt: 5}}`. A like comparison is written like this: `{title: {$like: 'om'}}`. Greater than or equals looks like this: `{created_at: {$gte: '2016-01-01'}}`.

See the wiki doc for [comparison operators](https://github.com/laran/GQL/wiki/Comparison-Operators) for the full set of operators.

Conditions containing an array for the value are interpreted as [IN conditions](https://github.com/laran/GQL/wiki/Comparison-Operators#in-comparisons). They will be converted to IN clauses when passed through `gql.applyTo(...)`.
### Negated Conditions

Conditions can be negated. All negative conditions are mapped in the following way: `{$not: {featured: true}}`.

Remember that the `$not` is always outside the property, condition and value. It's done this way because it allows the same string syntax (for GQL strings) and JSON structure for negation of nested filters as well as single conditions.
### Nested Filters (operator precedence)

Conditions can be grouped together with their own relative boolean logic and then that set of conditions can be nested within another set of conditions. The nested set of conditions would be represented as an array. That would look like this: `[{author_id: 5}, [{featured: true}, {$or: {created_at: {$gt: '2016-01-01'}}}]]`. In this example the second element in the outer array is also an array which represents a clause containing two conditions related to one another by OR boolean logic.

**Comment by kirrg001** [comment]
Hey @laran 👋

I'm sorry that you haven't got a reply. Thanks for your effort of writing this up 🙂

**GQL was replaced by [NQL](https://github.com/NexesJS/NQL). GQL is deprecated now.**

NQL is the new and better GQL. It makes use of the MongoDB's Query JSON format, which is explained [here](https://github.com/NexesJS/NQL-Lang/wiki). If you have any questions or ideas, feel free to raise an issue [here](https://github.com/NexesJS/NQL-Lang).
