### ISSUE TITLE
Filter for "not empty" columns

### ISSUE THREAD

**Issue by marcuspoehls** [TryGhost/GQL#20]
Hi @ErisDS 

I'm trying to filter posts based on a column (called `video`) where I want all the posts where the video column is not empty. Actually, I tried using the `video:-null` approach, but that won't work for posts where I removed a given video, because the column is empty now instead of `null`.

Can't find a way to filter only for posts where a given column value isn't empty.

Can you please help?

**Comment by ErisDS** [comment]
@marcuspoehls By all means, submit a fix to GQL. However, as `video` is your own custom field, perhaps you could also fix it by ensuring the field is set back to null?

I'm afraid I'm crazy busy with Ghost 1.0.0 and not going to have any more time for GQL until we next work on the API, which is scheduled for after the release of 1.0.0.

**Comment by marcuspoehls** [comment]
@ErisDS Your hint to set back the field to null was the piece I missed. Thanks for your reply and help!
