### ISSUE TITLE
Support for empty literals, strings and groups

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/GQL#36]
See: https://github.com/TryGhost/Ghost/issues/9258 & https://github.com/TryGhost/Casper/issues/382

I've seen this pop up a few times. If you use dynamic queries, there's no guarantee that you will get anything output, and then GQL will error.

Short term the solution is to put guards around dynamic queries, but I think we can do better in GQL.

**Comment by kirrg001** [comment]
GQL was replaced with [NQL](https://github.com/NexesJS/NQL/).

This issue is tracked [here](https://github.com/NexesJS/NQL-Lang/issues/3) now.
