### ISSUE TITLE
Improve error messages returned from Lexer & Parser

### ISSUE THREAD

**Issue by ErisDS** [TryGhost/GQL#4]
Currently, the error output has not been modified at all - and is just the standard output from JISON. The output when an error occurs looks like this:

When there's an error in the Lexer (this means a symbol cannot be interpreted as meaning something)
```
Lexical error on line 1. Unrecognized text.
slug:-=
------^
```

When there's an error in the Parser (this means a all the symbols are understood, but something appears in an unexpected place)
```
Parse error on line 1:
slug:->
------^
Expecting 'LBRACKET', 'NULL', 'TRUE', 'FALSE', 'NUMBER', 'LITERAL', 'STRING', got 'GT'
```

These error messages could use some improvement. 

First of all, there will only ever be one line, so it makes no sense to include the 'on line 1' part. Instead it would be more useful to say either nothing, or perhaps 'at character x', even though the diagram shows which character is causing the error.

Secondly, I don't know that it's particularly helpful to say `Lexical error` or `Parse error` - hardly anyone is going to get a benefit from this. 

Instead I think the IDEAL forms of error should be something like:

```
Query Error: unrecognized text "=" in filter at char 7
slug:-=
------^
```

and 

```
Query error, unexpected 'GT' in filter at char 7
slug:->
------^
Expecting one of: 'LBRACKET', 'NULL', 'TRUE', 'FALSE', 'NUMBER', 'LITERAL', 'STRING'
```

E.g. I think the error messages should both mention that they are Query or Filter errors (which is clearer?), one should mention 'unrecognized' and the other 'unexpected', but the different here is minor.

If possible, the Lexer error should also include the unrecognised symbol as shown. 

If possible, we should say which char the error is at, or say nothing at all about that.

----

How:

I believe it is possible to add custom error handling to JISON parsers, by overriding the `parseError` method as shown here: https://gist.github.com/GerHobbelt/e18f2ef8ee575d4ff49d#file-parser-wrapper-js-L49

Doing this should allow for the modification of the text in the messages, but it doesn't give access to extra information about which char is the bad one - especially not for the Lexer error. It may be possible to parse this info out of the error message, but not sure it's worth it.

Maybe worth proposing an improvement to the hash returned from the Lexer error in JISON?

**Comment by halfdan** [comment]
Dibs.
